# GET http://localhost:3001/users

# POST http://localhost:5001/users
# Content-Type: application/json

# {
#     "name": "Yuto",
#     "country":"Japan"
# }

# PUT http://localhost:5001/users
# Content-Type: application/json

# {
#     "id":4,
#     "name":"Arthur",
#     "country": "Canada"
# }

DELETE http://localhost:5001/users
Content-Type: application/json

{
    "id":5
}